version: "3"
services: 
  postgres:
    container_name: postgres-container
    image: postgres
    volumes: 
      - ./data:/data/db
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=root
  api:
    container_name: access-managemet
    image: node:15
    working_dir: /usr/src/access-management-api
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/access-management-api/dist
      - ./package.json:/usr/src/access-management-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"      
    links:
      - postgres
    environment: 
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/postgres